#!/bin/bash
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null; pwd)

eval $(grep '^COMPOSE_PROJECT_NAME=' "$DIR/.env")

"$DIR/dock" up -d
docker exec -ti "${COMPOSE_PROJECT_NAME}_shell_1" /bin/bash
