version: '2'
services:
  shell:
    build: https://github.com/fredZen/dev-env.git
    volumes:
     - .:/root
     - /var/run/docker.sock:/var/run/docker.sock
    tty: true
  jekyll:
    image: madduci/docker-github-pages:3.4
    volumes:
     - .:/site
    command: ['serve', '--watch', '--force_polling', '--host', '0.0.0.0', '--drafts']
    ports:
     - "4000:4000"
